#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
repo_root=$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null || (CDPATH= cd -- "$script_dir/.." && pwd))
cd "$repo_root"

if [ -f "SKILL.md" ] && [ -d "skills" ]; then
  canonical_root="skills"
  canonical_rel_prefix="../../../skills"
elif [ -f ".agents/skills/harness/SKILL.md" ] && [ -d ".agents/skills/harness/skills" ]; then
  canonical_root=".agents/skills/harness/skills"
  canonical_rel_prefix="../../../.agents/skills/harness/skills"
else
  echo "unable to resolve canonical skills directory" >&2
  exit 1
fi

projection_root=".claude/skills"

description_for() {
  file="$1"
  awk '
    index($0, "description: ") == 1 {
      print substr($0, length("description: ") + 1)
      exit
    }
  ' "$file"
}

name_for() {
  file="$1"
  awk '
    index($0, "name: ") == 1 {
      print substr($0, length("name: ") + 1)
      exit
    }
  ' "$file"
}

allowed_tools_for_slug() {
  slug="$1"
  case "$slug" in
    decision-pack|research-memo|governance-meeting|vision-meeting|requirements-meeting|brainstorming-session|acceptance-review)
      printf '%s\n' 'Read, Glob, Grep, Bash, WebSearch, WebFetch'
      ;;
    *)
      printf '%s\n' 'Read, Glob, Grep, Bash'
      ;;
  esac
}

mkdir -p "$projection_root"

for canonical_skill in "$canonical_root"/*/SKILL.md; do
  [ -f "$canonical_skill" ] || continue

  slug=$(basename "$(dirname "$canonical_skill")")
  projection_dir="$projection_root/$slug"
  projection_file="$projection_dir/SKILL.md"
  canonical_abs="$repo_root/$canonical_skill"
  canonical_rel="$canonical_rel_prefix/$slug/SKILL.md"
  skill_name=$(name_for "$canonical_skill")
  skill_description=$(description_for "$canonical_skill")
  allowed_tools=$(allowed_tools_for_slug "$slug")

  mkdir -p "$projection_dir"

  cat >"$projection_file" <<EOF
---
name: $skill_name
description: $skill_description
disable-model-invocation: false
allowed-tools: $allowed_tools
---

AUTO-GENERATED projection. Do not edit this file manually.

Canonical skill source:

- [$canonical_rel]($canonical_abs)

Follow the canonical repo skill above as the single source of truth for workflow, inputs, outputs, and constraints.
This Claude projection exists only for provider discovery and tool binding.
EOF
done

for projection_dir in "$projection_root"/*; do
  [ -d "$projection_dir" ] || continue
  slug=$(basename "$projection_dir")
  if [ ! -f "$canonical_root/$slug/SKILL.md" ]; then
    rm -rf "$projection_dir"
  fi
done

echo "synced Claude skill projections from $canonical_root to $projection_root"
