#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
repo_root=$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null || (CDPATH= cd -- "$script_dir/.." && pwd))
cd "$repo_root"

if [ -f "SKILL.md" ] && [ -d "roles" ]; then
  canonical_root="roles"
  canonical_rel_prefix="../../roles"
elif [ -f ".agents/skills/harness/SKILL.md" ] && [ -d ".agents/skills/harness/roles" ]; then
  canonical_root=".agents/skills/harness/roles"
  canonical_rel_prefix="../../.agents/skills/harness/roles"
else
  echo "unable to resolve canonical roles directory" >&2
  exit 1
fi

claude_root=".claude/agents"
codex_root=".codex/agents"

frontmatter_value() {
  file="$1"
  key="$2"
  awk -v key="$key" '
    NR == 1 && $0 == "---" { in_frontmatter = 1; next }
    in_frontmatter && $0 == "---" { exit }
    in_frontmatter && index($0, key ": ") == 1 {
      print substr($0, length(key ": ") + 1)
      exit
    }
  ' "$file"
}

role_body() {
  file="$1"
  awk '
    seen_heading { print }
    /^## Canonical Instructions$/ { seen_heading = 1; next }
  ' "$file"
}

toml_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

yaml_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

mkdir -p "$claude_root" "$codex_root"

for canonical_role in "$canonical_root"/*.md; do
  [ -f "$canonical_role" ] || continue
  [ "$(basename "$canonical_role")" = "README.md" ] && continue

  schema_version=$(frontmatter_value "$canonical_role" "schema_version")
  slug=$(frontmatter_value "$canonical_role" "slug")
  claude_file=$(frontmatter_value "$canonical_role" "claude_file")
  claude_name=$(frontmatter_value "$canonical_role" "claude_name")
  claude_description=$(frontmatter_value "$canonical_role" "claude_description")
  claude_tools=$(frontmatter_value "$canonical_role" "claude_tools")
  claude_model=$(frontmatter_value "$canonical_role" "claude_model")
  codex_file=$(frontmatter_value "$canonical_role" "codex_file")
  codex_name=$(frontmatter_value "$canonical_role" "codex_name")
  codex_description=$(frontmatter_value "$canonical_role" "codex_description")
  codex_model=$(frontmatter_value "$canonical_role" "codex_model")
  codex_reasoning=$(frontmatter_value "$canonical_role" "codex_reasoning_effort")
  codex_sandbox=$(frontmatter_value "$canonical_role" "codex_sandbox_mode")
  codex_nicknames=$(frontmatter_value "$canonical_role" "codex_nicknames")
  body=$(role_body "$canonical_role" | sed '/./,$!d')
  canonical_abs="$repo_root/$canonical_role"
  canonical_rel="$canonical_rel_prefix/$(basename "$canonical_role")"

  [ "$schema_version" = "1" ] || {
    echo "unsupported schema_version '$schema_version' in $canonical_role" >&2
    exit 1
  }

  cat >"$claude_root/$claude_file" <<EOF
---
name: $(yaml_escape "$claude_name")
description: $(yaml_escape "$claude_description")
tools: $(yaml_escape "$claude_tools")
model: $(yaml_escape "$claude_model")
---

AUTO-GENERATED projection. Do not edit this file manually.

Canonical role source:

- [$canonical_rel]($canonical_abs)

$body
EOF

  cat >"$codex_root/$codex_file" <<EOF
name = "$(toml_escape "$codex_name")"
description = "$(toml_escape "$codex_description")"
model = "$(toml_escape "$codex_model")"
model_reasoning_effort = "$(toml_escape "$codex_reasoning")"
sandbox_mode = "$(toml_escape "$codex_sandbox")"
nickname_candidates = ["$(printf '%s' "$codex_nicknames" | sed 's/, */,/g; s/,/","/g')"]
developer_instructions = """
AUTO-GENERATED projection from $canonical_abs. Do not edit this file manually.

$body
"""
EOF

  [ -n "$slug" ] || {
    echo "missing slug in $canonical_role" >&2
    exit 1
  }
done

echo "synced Claude/Codex agent projections from $canonical_root"
